(function (global) {
  "use strict";

  const DATA = global.DISYPHER_BROWSER_DATA;
  if (!DATA) throw new Error("Disypher browser data is missing");
  const ALPHABET = "abcdefghijklmnopqrstuvwxyz";
  const SENTENCE_MARKS = new Set(".,;:!?'\"()[]{}«»…-–—");
  const AFFINE_KEYS = [1,3,5,7,9,11,15,17,19,21,23,25];
  const MIN_RELIABLE_LENGTH = 40, MAX_KEY_LENGTH = 20;
  const CHI_WEIGHT=.30, WORD_WEIGHT=.50, COUNT_WEIGHT=.20;
  const WORD_REFERENCE=.55, WORD_EVIDENCE_REFERENCE=25, CHI_RELIABLE_LENGTH=200;
  const TIE_EPSILON=.02, MIN_COLUMN_LENGTH=12, COLUMN_IOC_THRESHOLD=.058, MULTIPLE_IOC_MARGIN=.008;
  const LANGUAGES = {};
  const BANKS = DATA.banks;
  const MORSE = {a:".-",b:"-...",c:"-.-.",d:"-..",e:".",f:"..-.",g:"--.",h:"....",i:"..",j:".---",k:"-.-",l:".-..",m:"--",n:"-.",o:"---",p:".--.",q:"--.-",r:".-.",s:"...",t:"-",u:"..-",v:"...-",w:".--",x:"-..-",y:"-.--",z:"--..",0:"-----",1:".----",2:"..---",3:"...--",4:"....-",5:".....",6:"-....",7:"--...",8:"---..",9:"----."};
  const MORSE_REVERSE = Object.fromEntries(Object.entries(MORSE).map(([k,v])=>[v,k]));

  function registerLanguage(code,name,frequencies,words,builtin=false){
    LANGUAGES[code]={code,name,frequencies:{...frequencies},words:new Set(words.map(w=>String(w).trim().toLowerCase()).filter(w=>w.length>1)),builtin};
  }
  for(const entry of Object.values(DATA.languages)) registerLanguage(entry.code,entry.name,entry.frequencies,entry.words,entry.builtin);
  function loadBank(bankOrCode){
    const bank=typeof bankOrCode==="string" ? BANKS[bankOrCode] : bankOrCode;
    if(!bank) throw new Error("bank not found");
    if(bank.universal){ for(const lang of Object.values(LANGUAGES)) for(const word of bank.words) if(String(word).trim().length>1) lang.words.add(String(word).trim().toLowerCase()); return; }
    registerLanguage(bank.code,bank.name,bank.frequencies||{},bank.words||[],false);
  }
  const mod=(n,m)=>((n%m)+m)%m;
  const gcd=(a,b)=>b?gcd(b,a%b):Math.abs(a);
  function inverseMod(a,m){ for(let x=1;x<m;x++) if(mod(a*x,m)===1)return x; throw new Error(`multiplier ${a} is not invertible modulo ${m}`); }
  function lettersOnly(text){return [...String(text).toLowerCase()].filter(c=>ALPHABET.includes(c)).join("");}
  function isLatinLetter(c){return c.length===1&&ALPHABET.includes(c.toLowerCase());}
  function isDigit(c){return c>="0"&&c<="9";}
  function chiSquared(text,language){const s=lettersOnly(text);if(!s)return Infinity;const total=s.length, counts={};for(const c of s)counts[c]=(counts[c]||0)+1;let score=0;for(const c of ALPHABET){const observed=counts[c]||0, expected=(LANGUAGES[language].frequencies[c]||0)*total/100;if(expected>0)score+=(observed-expected)**2/expected;}return score/total;}
  function tokenize(text){return (String(text).toLowerCase().match(/[a-z]+/g)||[]).filter(w=>w.length>1);}
  function wordHits(text,language){const words=tokenize(text);if(!words.length)return[0,0];const hits=words.filter(w=>LANGUAGES[language].words.has(w));return[hits.length/words.length,hits.reduce((n,w)=>n+w.length-1,0)];}
  function indexOfCoincidence(text){const s=lettersOnly(text),n=s.length;if(n<2)return 0;const counts={};for(const c of s)counts[c]=(counts[c]||0)+1;return Object.values(counts).reduce((a,v)=>a+v*(v-1),0)/(n*(n-1));}
  function plausibility(text){let bestScore=0,bestLanguage=Object.keys(LANGUAGES)[0];const measurable=Math.min(lettersOnly(text).length/CHI_RELIABLE_LENGTH,1),chiWeight=CHI_WEIGHT*measurable,countWeight=COUNT_WEIGHT+(CHI_WEIGHT-chiWeight);for(const language of Object.keys(LANGUAGES)){const chi=chiSquared(text,language),[ratio,evidence]=wordHits(text,language);const score=chiWeight*Math.exp(-chi/.6)+WORD_WEIGHT*Math.min(ratio/WORD_REFERENCE,1)+countWeight*Math.min(evidence/WORD_EVIDENCE_REFERENCE,1);if(score>bestScore){bestScore=score;bestLanguage=language;}}return[bestScore,bestLanguage];}
  function transformScope(before,after){const empty={changed:[],untouched:[]};if(!before||before.length!==after.length)return empty;const tests=[['letters',isLatinLetter],['digits',isDigit],['symbols',c=>!isLatinLetter(c)&&!isDigit(c)&&!(/\s/u.test(c))&&!SENTENCE_MARKS.has(c)]],present=new Set(),changed=new Set();for(let i=0;i<before.length;i++)for(const[name,test]of tests)if(test(before[i])){present.add(name);if(before[i]!==after[i])changed.add(name);}if(!present.size)return empty;return{changed:tests.map(x=>x[0]).filter(x=>changed.has(x)),untouched:tests.map(x=>x[0]).filter(x=>present.has(x)&&!changed.has(x))};}

  function caesar(text,shift){return[...text].map(c=>{if(!isLatinLetter(c))return c;const base=c===c.toUpperCase()?65:97;return String.fromCharCode(base+mod(c.charCodeAt(0)-base+Number(shift),26));}).join("");}
  function atbash(text){return[...text].map(c=>{if(!isLatinLetter(c))return c;const base=c===c.toUpperCase()?65:97;return String.fromCharCode(base+25-(c.charCodeAt(0)-base));}).join("");}
  function affine(text,a=5,b=8,decode=false){a=Number(a);b=Number(b);if(gcd(a,26)!==1)throw new Error(`multiplier ${a} is not invertible modulo 26`);const inv=inverseMod(a,26);return[...text].map(c=>{if(!isLatinLetter(c))return c;const base=c===c.toUpperCase()?65:97,x=c.charCodeAt(0)-base,y=decode?mod(inv*(x-b),26):mod(a*x+b,26);return String.fromCharCode(base+y);}).join("");}
  function rot5(text,shift=5){return[...text].map(c=>isDigit(c)?String.fromCharCode(48+mod(c.charCodeAt(0)-48+Number(shift),10)):c).join("");}
  function rot18(text){return rot5(caesar(text,13));}
  function rot47(text,shift=47){return[...text].map(c=>{const n=c.charCodeAt(0);return n>=33&&n<=126?String.fromCharCode(33+mod(n-33+Number(shift),94)):c;}).join("");}
  function vigenere(text,key,decode=false,autokey=false){const keyLetters=[...lettersOnly(key)];if(!keyLetters.length)return text;const stream=[...keyLetters],out=[];let index=0;for(const c of text){if(isLatinLetter(c)){const base=c===c.toUpperCase()?65:97,shift=stream[index].charCodeAt(0)-97,value=mod(c.charCodeAt(0)-base+(decode?-shift:shift),26);out.push(String.fromCharCode(base+value));if(autokey)stream.push(decode?String.fromCharCode(97+value):c.toLowerCase());else if(index+1>=stream.length)stream.push(...keyLetters);index++;}else out.push(c);}return out.join("");}
  function beaufort(text,key){const k=lettersOnly(key);if(!k)return text;let i=0;return[...text].map(c=>{if(!isLatinLetter(c))return c;const base=c===c.toUpperCase()?65:97,kv=k.charCodeAt(i++%k.length)-97;return String.fromCharCode(base+mod(kv-(c.charCodeAt(0)-base),26));}).join("");}
  function railPattern(rails,length,offset=0){const cycle=[];for(let i=0;i<rails;i++)cycle.push(i);for(let i=rails-2;i>0;i--)cycle.push(i);return Array.from({length},(_,i)=>cycle[mod(i+Number(offset),cycle.length)]);}
  function railFence(text,rails,decode=false,offset=0){rails=Number(rails);if(rails<2||!text)return text;const pos=railPattern(rails,text.length,offset);if(!decode){const rows=Array(rails).fill("");[...text].forEach((c,i)=>rows[pos[i]]+=c);return rows.join("");}const counts=Array.from({length:rails},(_,r)=>pos.filter(x=>x===r).length),rows=[];let cursor=0;for(const count of counts){rows.push(text.slice(cursor,cursor+count));cursor+=count;}const ix=Array(rails).fill(0),out=[];for(const rail of pos)out.push(rows[rail][ix[rail]++]);return out.join("");}
  function columnar(text,key,decode=false,pad="x"){const k=lettersOnly(key);if(!k)return text;const width=k.length,order=Array.from({length:width},(_,i)=>i).sort((a,b)=>k[a].localeCompare(k[b])||a-b);if(!decode){const padded=text+pad.repeat(mod(-text.length,width)),cols=Array.from({length:width},(_,i)=>[...padded].filter((_,j)=>j%width===i).join(""));return order.map(i=>cols[i]).join("");}const height=Math.floor(text.length/width),cols=Array(width).fill("");let cursor=0;for(const i of order){cols[i]=text.slice(cursor,cursor+height);cursor+=height;}let out="";for(let row=0;row<height;row++)for(const col of cols)out+=col[row];return out;}

  function toMorse(text,letterSep=" ",wordSep=" / "){return String(text).toLowerCase().trim().split(/\s+/).map(word=>[...word].filter(c=>MORSE[c]).map(c=>MORSE[c]).join(letterSep)).filter(Boolean).join(wordSep);}
  function fromMorse(text,wordSep=null,letterSep=" "){if(wordSep){const words=String(text).split(wordSep).map(chunk=>(letterSep?chunk.split(letterSep):chunk.trim().split(/\s+/)).filter(Boolean)).filter(x=>x.length);if(!words.length||words.some(codes=>codes.some(c=>!MORSE_REVERSE[c])))throw new Error("invalid morse sequence");return words.map(codes=>codes.map(c=>MORSE_REVERSE[c]).join("")).join(" ").trim();}let normalized=String(text).replace(/\|/g,"/").replace(/_/g,"-").replace(/\s{2,}/g," / ");const out=[];for(const token of normalized.replace(/\//g," / ").trim().split(/\s+/)){if(token==="/")out.push(" ");else if(MORSE_REVERSE[token])out.push(MORSE_REVERSE[token]);else throw new Error("invalid morse sequence");}return out.join("").trim();}
  const encoder=new TextEncoder(),decoder=new TextDecoder("utf-8",{fatal:true});
  function bytesToBinary(bytes){let s="";for(const b of bytes)s+=String.fromCharCode(b);return s;}
  function toBase64(text,urlsafe=false){let out=btoa(bytesToBinary(encoder.encode(text)));return urlsafe?out.replace(/\+/g,"-").replace(/\//g,"_"):out;}
  function decodeBase64(text){let s=String(text).replace(/\s/g,"");if(s.length<4)throw new Error("too short for base64");s=s.replace(/-/g,"+").replace(/_/g,"/");if(!/^[A-Za-z0-9+/]+={0,2}$/.test(s))throw new Error("characters outside the base64 alphabet");s+="=".repeat(mod(-s.length,4));return decoder.decode(Uint8Array.from(atob(s),c=>c.charCodeAt(0)));}
  function toHex(text,sep="",prefix="",upper=false){return [...encoder.encode(text)].map(b=>prefix+b.toString(16).padStart(2,"0")[upper?"toUpperCase":"toLowerCase"]()).join(sep);}
  function decodeHex(text,sep=null,prefix=null){let s=String(text);if(prefix)s=s.split(prefix).join("");if(sep)s=s.split(sep).join("");if(!sep&&!prefix)s=s.replace(/0x|[\s,:;-]/gi,"");else s=s.replace(/\s/g,"");if(s.length<4||s.length%2)throw new Error("length incompatible with hexadecimal");if(!/^[0-9a-f]+$/i.test(s))throw new Error("invalid hexadecimal");const out=decoder.decode(Uint8Array.from(s.match(/../g),x=>parseInt(x,16)));if(!printable(out))throw new Error("hexadecimal does not yield readable text");return out;}
  function toBinary(text,sep=" ",bits=8){return [...encoder.encode(text)].map(b=>b.toString(2).padStart(Number(bits),"0")).join(sep);}
  function printable(text){return !!text&&[...text].every(c=>c==="\n"||c==="\t"||(c.codePointAt(0)>=32&&c.codePointAt(0)<127)||c.codePointAt(0)>160);}
  function decodeBinary(text,bits=null,sep=null){const cleaned=String(text).trim(),tokens=sep?cleaned.split(sep).filter(Boolean):cleaned.split(/[\s,;|-]+/);if(tokens.length>=2&&tokens.every(t=>/^[01]{7,8}$/.test(t)))return tokens.map(t=>String.fromCharCode(parseInt(t,2))).join("");const stream=sep?cleaned.split(sep).join(""):cleaned.replace(/[\s,;|-]/g,"");if(stream.length<14||!/^[01]+$/.test(stream))throw new Error("not binary bytes");for(const width of bits?[Number(bits)]:[8,7]){if(stream.length%width)continue;const out=stream.match(new RegExp(`.{${width}}`,"g")).map(x=>String.fromCharCode(parseInt(x,2))).join("");if([...out].every(c=>c==="\n"||c==="\t"||(c.charCodeAt(0)>=32&&c.charCodeAt(0)<127)))return out;}throw new Error("binary word width cannot be determined");}

  function columnShift(column,language="en"){let best=0,bestScore=Infinity;for(let shift=0;shift<26;shift++){const decoded=[...column].map(c=>String.fromCharCode(97+mod(c.charCodeAt(0)-97-shift,26))).join(""),score=chiSquared(decoded,language);if(score<bestScore){bestScore=score;best=shift;}}return best;}
  function columnBeaufort(column,language="en"){let best=0,bestScore=Infinity;for(let k=0;k<26;k++){const decoded=[...column].map(c=>String.fromCharCode(97+mod(k-(c.charCodeAt(0)-97),26))).join(""),score=chiSquared(decoded,language);if(score<bestScore){bestScore=score;best=k;}}return best;}
  function keyLength(letters,max){const scores={};for(let length=1;length<=max;length++){if(Math.floor(letters.length/length)<MIN_COLUMN_LENGTH)break;let total=0;for(let i=0;i<length;i++)total+=indexOfCoincidence([...letters].filter((_,j)=>j%length===i).join(""));scores[length]=total/length;}const plausible=Object.keys(scores).map(Number).filter(k=>scores[k]>=COLUMN_IOC_THRESHOLD);if(!plausible.length)return null;let best=Math.min(...plausible);for(let multiple=2;multiple<=Math.floor(max/best);multiple++){const candidate=best*multiple;if((scores[candidate]||0)>scores[best]+MULTIPLE_IOC_MARGIN)best=candidate;}return best;}
  function refineKey(text,key){let current=[...key];for(let pass=0;pass<2;pass++){let changed=false;for(let position=0;position<current.length;position++){let bestLetter=current[position],bestScore=plausibility(vigenere(text,current.join(""),true))[0];for(const letter of ALPHABET){if(letter===current[position])continue;const trial=[...current];trial[position]=letter;const score=plausibility(vigenere(text,trial.join(""),true))[0];if(score>bestScore){bestScore=score;bestLetter=letter;}}if(bestLetter!==current[position]){current[position]=bestLetter;changed=true;}}if(!changed)break;}return current.join("");}
  function crackVigenere(text){const letters=lettersOnly(text);if(letters.length<30)return null;const length=keyLength(letters,MAX_KEY_LENGTH);if(length===null)return null;const language=chiSquared(letters,"en")<chiSquared(letters,"fr")?"en":"fr";let key="";for(let i=0;i<length;i++)key+=String.fromCharCode(97+columnShift([...letters].filter((_,j)=>j%length===i).join(""),language));key=refineKey(text,key);return[key,vigenere(text,key,true)];}
  function crackBeaufort(text){const letters=lettersOnly(text);if(letters.length<30)return null;const length=keyLength(letters,MAX_KEY_LENGTH);if(length===null)return null;const language=chiSquared(letters,"en")<chiSquared(letters,"fr")?"en":"fr";let key="";for(let i=0;i<length;i++)key+=String.fromCharCode(97+columnBeaufort([...letters].filter((_,j)=>j%length===i).join(""),language));return[key,beaufort(text,key)];}
  function permutations(n){const out=[];function walk(prefix,left){if(!left.length){out.push(prefix);return;}for(let i=0;i<left.length;i++)walk([...prefix,left[i]],[...left.slice(0,i),...left.slice(i+1)]);}walk([],Array.from({length:n},(_,i)=>i));return out;}
  function pick(trials){let best=trials[0];for(const trial of trials.slice(1))if(trial[0]>best[0]+TIE_EPSILON)best=trial;return best;}
  function variantsOf(trials,chosen){const seen=new Set([chosen[2].trim().toLowerCase()]),out=[];for(const [score,params,plaintext] of [...trials].sort((a,b)=>b[0]-a[0])){const sig=plaintext.trim().toLowerCase();if(seen.has(sig))continue;seen.add(sig);out.push({params,plaintext:plaintext.slice(0,220),confidence:+score.toFixed(4)});if(out.length>=400)break;}return out;}
  function candidate(cipher,label,plaintext,confidence,language,detail="",params={},variants=[],pinned=false){return{cipher,label,plaintext,confidence,language,detail,params,variants,pinned,scope:{changed:[],untouched:[]}};}
  function selectedValues(pins,name,key,defaults,cast=x=>x){const given=pins?.[name]?.[key];if(given===undefined||given===null||given===""||(Array.isArray(given)&&!given.length))return[defaults,false];const values=Array.isArray(given)?given:[given];return[values.map(cast),true];}
  const labelFor={base64:"Base64",hex:"Hexadecimal",binary:"Binary",morse:"Morse",reverse:"Reversed text",atbash:"Atbash",rot47:"ROT47",rot5:"ROT5",rot18:"ROT18",affine:"Affine",railfence:"Rail fence",vigenere:"Vigenère",beaufort:"Beaufort",columnar:"Columnar"};
  function analyse(raw,only=null,pins=null){const text=String(raw).trim(),wanted=n=>!only||only.includes(n),result={candidates:[],reliable:true,sampleLength:lettersOnly(text).length,indexOfCoincidence:+indexOfCoincidence(text).toFixed(4),reason:"",reasonData:{},polyalphabetic:false,note:"",alreadyPlain:false};if(!text){result.reliable=false;result.reason="empty";result.note="No text provided.";return result;}const candidates=[];
    if(wanted("base64"))try{const d=decodeBase64(text);if(d.trim()){const[s,l]=plausibility(d);candidates.push(candidate("base64",labelFor.base64,d,Math.min(s+.25,1),l,"Structurally valid decoding"));}}catch{}
    if(wanted("hex")){const[seps,sp]=selectedValues(pins,"hex","sep",[null],String),[prefixes,pp]=selectedValues(pins,"hex","prefix",[null],String);try{const d=decodeHex(text,seps[0],prefixes[0]);if(d.trim()){const[s,l]=plausibility(d),p={};if(seps[0])p.sep=seps[0];if(prefixes[0])p.prefix=prefixes[0];candidates.push(candidate("hex",labelFor.hex,d,Math.min(s+.25,1),l,"Structurally valid decoding",p,[],sp||pp));}}catch{}}
    if(wanted("morse")){const[ws,wp]=selectedValues(pins,"morse","word_sep",[null],String),[ls,lp]=selectedValues(pins,"morse","letter_sep",[" "],String);try{const d=fromMorse(text,ws[0],ls[0]);if(d.trim()){const[s,l]=plausibility(d),p={};if(ws[0])p.word_sep=ws[0];if(lp)p.letter_sep=ls[0];candidates.push(candidate("morse",labelFor.morse,d,Math.min(s+.25,1),l,"Structurally valid decoding",p,[],wp||lp));}}catch{}}
    if(wanted("binary")){const[widths,wPin]=selectedValues(pins,"binary","bits",[8,7],Number),[seps,sPin]=selectedValues(pins,"binary","sep",[null],String),trials=[];for(const width of widths)try{const d=decodeBinary(text,width,seps[0]);if(d.trim()){const[s,l]=plausibility(d);trials.push([Math.min(s+.25,1),{bits:width},d,l]);}}catch{}if(trials.length){let chosen=pick(trials),p={...chosen[1]};if(seps[0])p.sep=seps[0];candidates.push(candidate("binary",labelFor.binary,chosen[2],chosen[0],chosen[3],`${p.bits} bits`,p,variantsOf(trials,chosen),wPin||sPin));}}
    if(wanted("reverse")){const d=[...text].reverse().join(""),[s,l]=plausibility(d);candidates.push(candidate("reverse",labelFor.reverse,d,s,l));}
    if(wanted("atbash")){const d=atbash(text),[s,l]=plausibility(d);candidates.push(candidate("atbash",labelFor.atbash,d,s,l));}
    if(wanted("rot47")){const[shifts,pin]=selectedValues(pins,"rot47","shift",[47],Number),trials=shifts.map(shift=>{const d=rot47(text,-shift),[s,l]=plausibility(d);return[s,{shift},d,l];}),ch=pick(trials);candidates.push(candidate("rot47",labelFor.rot47,ch[2],ch[0],ch[3],`shift ${ch[1].shift}`,ch[1],variantsOf(trials,ch),pin));}
    if(wanted("caesar")){const[shifts,pin]=selectedValues(pins,"caesar","shift",Array.from({length:25},(_,i)=>i+1),Number),trials=shifts.map(shift=>{const d=caesar(text,-shift),[s,l]=plausibility(d);return[s,{shift},d,l];}),ch=pick(trials);candidates.push(candidate("caesar",ch[1].shift===13?"ROT13":"Caesar",ch[2],ch[0],ch[3],`shift ${ch[1].shift}`,ch[1],variantsOf(trials,ch),pin));}
    for(const[name,fn]of[["rot5",rot5],["rot18",rot18]])if(wanted(name)){const d=fn(text),[s,l]=plausibility(d);candidates.push(candidate(name,labelFor[name],d,s,l));}
    if(wanted("affine")){const[as,ap]=selectedValues(pins,"affine","a",AFFINE_KEYS.filter(x=>x!==1),Number),[bs,bp]=selectedValues(pins,"affine","b",Array.from({length:26},(_,i)=>i),Number),trials=[];for(const a of as)if(gcd(a,26)===1)for(const b of bs){const d=affine(text,a,b,true),[s,l]=plausibility(d);trials.push([s,{a,b},d,l]);}if(trials.length){const ch=pick(trials);candidates.push(candidate("affine",labelFor.affine,ch[2],ch[0],ch[3],`a=${ch[1].a}, b=${ch[1].b}`,ch[1],variantsOf(trials,ch),ap||bp));}}
    if(wanted("railfence")){const[rails,rp]=selectedValues(pins,"railfence","rails",[2,3,4,5,6,7],Number),sources=raw===text?[raw]:[text,raw],trials=[];let op=false;for(const source of sources)for(const rail of rails){if(rail<2)continue;const[offsets,p]=selectedValues(pins,"railfence","offset",Array.from({length:2*rail-2},(_,i)=>i),Number);op=op||p;for(const offset of offsets){const d=railFence(source,rail,true,offset),[s,l]=plausibility(d);trials.push([s,{rails:rail,offset},d,l]);}}if(trials.length){const ch=pick(trials),detail=`${ch[1].rails} rails`+(ch[1].offset?`, offset ${ch[1].offset}`:"");candidates.push(candidate("railfence",labelFor.railfence,ch[2],ch[0],ch[3],detail,ch[1],variantsOf(trials,ch),rp||op));}}
    if(wanted("vigenere")){const[keys,kp]=selectedValues(pins,"vigenere","key",[],String),[autos,ap]=selectedValues(pins,"vigenere","autokey",[false],Boolean);if(kp){const trials=[];for(const key of keys)for(const autokey of autos){const d=vigenere(text,key,true,autokey),[s,l]=plausibility(d),p={key};if(autokey)p.autokey=true;trials.push([s,p,d,l]);}const ch=pick(trials);candidates.push(candidate("vigenere",labelFor.vigenere,ch[2],ch[0],ch[3],`key \"${ch[1].key}\"`,ch[1],variantsOf(trials,ch),true));}else{const cracked=crackVigenere(text);if(cracked){const[s,l]=plausibility(cracked[1]);candidates.push(candidate("vigenere",labelFor.vigenere,cracked[1],s,l,`recovered key \"${cracked[0]}\"`,{key:cracked[0]}));}}}
    if(wanted("beaufort")){const[keys,kp]=selectedValues(pins,"beaufort","key",[],String);if(kp){const trials=keys.map(key=>{const d=beaufort(text,key),[s,l]=plausibility(d);return[s,{key},d,l];}),ch=pick(trials);candidates.push(candidate("beaufort",labelFor.beaufort,ch[2],ch[0],ch[3],`key \"${ch[1].key}\"`,ch[1],variantsOf(trials,ch),true));}else{const cracked=crackBeaufort(text);if(cracked){const[s,l]=plausibility(cracked[1]);candidates.push(candidate("beaufort",labelFor.beaufort,cracked[1],s,l,`recovered key \"${cracked[0]}\"`,{key:cracked[0]}));}}}
    if(wanted("columnar")){const[keys,kp]=selectedValues(pins,"columnar","key",[],String),[widths,wp]=selectedValues(pins,"columnar","width",[2,3,4,5],Number),sources=raw===text?[raw]:[text,raw],trials=[];if(kp){for(const source of sources)for(const key of keys){const d=columnar(source,key,true),[s,l]=plausibility(d);trials.push([s,{key},d,l]);}}else for(const source of sources)for(const width of widths){if(width<2||lettersOnly(source).length<width*2)continue;for(const order of permutations(width)){let key="";for(let i=0;i<width;i++)key+=String.fromCharCode(97+order.indexOf(i));const d=columnar(source,key,true),[s,l]=plausibility(d);trials.push([s,{key,width},d,l]);}}if(trials.length){const ch=pick(trials);candidates.push(candidate("columnar",labelFor.columnar,ch[2],ch[0],ch[3],`key \"${ch[1].key}\"`,ch[1],variantsOf(trials,ch),kp||wp));}}
    for(const c of candidates)c.scope=transformScope(text,c.plaintext);candidates.sort((a,b)=>b.confidence-a.confidence);const seen=new Set([text.trim().toLowerCase()]),unique=[];for(const c of candidates){const sig=c.plaintext.trim().toLowerCase();if(seen.has(sig)&&!c.pinned)continue;seen.add(sig);unique.push(c);}const scored=[...unique];unique.sort((a,b)=>(Number(!a.pinned)-Number(!b.pinned))||(b.confidence-a.confidence));for(const c of unique)c.confidence=+c.confidence.toFixed(4);result.candidates=unique;const evidenceLength=scored.length?lettersOnly(scored[0].plaintext).length:result.sampleLength,[sourceScore]=plausibility(text);if(sourceScore>=.45&&result.sampleLength>=MIN_RELIABLE_LENGTH){result.alreadyPlain=true;result.reason="already_plain";result.note="This text is already readable: nothing suggests it is encrypted. The hypotheses below are kept for comparison only.";return result;}if(evidenceLength<MIN_RELIABLE_LENGTH){result.reliable=false;result.reason="short_sample";result.reasonData={length:evidenceLength,minimum:MIN_RELIABLE_LENGTH};result.note=`Short sample (${evidenceLength} letters). Statistical analysis is unreliable below ${MIN_RELIABLE_LENGTH} letters — the candidates below are indicative.`;}else if(!scored.length||scored[0].confidence<.35){result.reliable=false;result.reason="no_match";result.note="No convincing hypothesis. The text may use a method not covered here, or a key that could not be recovered.";}else if(scored.length>1&&scored[0].confidence-scored[1].confidence<.08){result.reliable=false;result.reason="ambiguous";result.note="Two hypotheses are too close to separate. A longer text would settle it.";}if(evidenceLength>=MIN_RELIABLE_LENGTH&&(!scored.length||scored[0].confidence<.5)&&result.indexOfCoincidence<.05){result.polyalphabetic=true;result.note+=(result.note?" ":"")+"The index of coincidence is low: the cipher is polyalphabetic. Vigenère with a short key is broken automatically; a long key, an autokey variant or a stream cipher is not.";}return result;
  }

  function encode(text,cipher,params={}){switch(cipher){case"caesar":return caesar(text,params.shift??3);case"rot13":return caesar(text,13);case"rot5":return rot5(text);case"rot18":return rot18(text);case"rot47":return rot47(text,params.shift??47);case"atbash":return atbash(text);case"affine":return affine(text,params.a??5,params.b??8);case"vigenere":return vigenere(text,params.key??"",false,params.autokey??false);case"beaufort":return beaufort(text,params.key??"");case"reverse":return[...text].reverse().join("");case"railfence":return railFence(text,params.rails??3,false,params.offset??0);case"columnar":return columnar(text,params.key??"",false,params.pad??"x");case"base64":return toBase64(text,params.urlsafe??false);case"hex":return toHex(text,params.sep??"",params.prefix??"",params.upper??false);case"binary":return toBinary(text,params.sep??" ",params.bits??8);case"morse":return toMorse(text,params.letter_sep??" ",params.word_sep??" / ");default:throw new Error(`unknown cipher: ${cipher}`);}}
  function decodeWithKey(text,cipher,params={}){switch(cipher){case"caesar":return caesar(text,-(params.shift??3));case"rot13":return caesar(text,13);case"rot5":return rot5(text,-5);case"rot18":return rot18(text);case"rot47":return rot47(text,-(params.shift??47));case"atbash":return atbash(text);case"affine":return affine(text,params.a??5,params.b??8,true);case"vigenere":return vigenere(text,params.key??"",true,params.autokey??false);case"beaufort":return beaufort(text,params.key??"");case"reverse":return[...text].reverse().join("");case"railfence":return railFence(text,params.rails??3,true,params.offset??0);case"columnar":return columnar(text,params.key??"",true);case"base64":return decodeBase64(text);case"hex":return decodeHex(text);case"binary":return decodeBinary(text);case"morse":return fromMorse(text);default:throw new Error(`unknown cipher: ${cipher}`);}}
  function roundTripLoss(text,cipher,params={}){let restored;try{restored=decodeWithKey(encode(text,cipher,params),cipher,params);}catch{return [];}const families=[["letters",c=>/\p{L}/u.test(c)],["digits",isDigit],["punctuation",c=>SENTENCE_MARKS.has(c)],["symbols",c=>!/\p{L}|\d|\s/u.test(c)&&!SENTENCE_MARKS.has(c)]],lost=[];for(const[name,test]of families)if([...text].filter(test).length>[...restored].filter(test).length)lost.push(name);if([...text].some(c=>/\p{Lu}/u.test(c))&&![...restored].some(c=>/\p{Lu}/u.test(c)))lost.push("case");return lost;}
  function encodeStages(text,steps){const stages=[];let current=text;for(const step of steps){const previous=current,params=step.params||{};current=encode(current,step.cipher,params);stages.push({cipher:step.cipher,params,output:current,scope:transformScope(previous,current),lost:roundTripLoss(previous,step.cipher,params)});}return stages;}
  function selfTest(){const sample="Attack the bridge at 06:30, now!";const vectors=[["caesar",{shift:7}],["rot13",{}],["rot5",{}],["rot18",{}],["rot47",{}],["atbash",{}],["affine",{a:5,b:8}],["vigenere",{key:"disyner"}],["vigenere",{key:"key",autokey:true}],["beaufort",{key:"disyner"}],["reverse",{}],["railfence",{rails:4,offset:2}],["columnar",{key:"zebra"}],["base64",{}],["hex",{}],["binary",{}]];for(const[cipher,params]of vectors){const encrypted=encode(sample,cipher,params),restored=decodeWithKey(encrypted,cipher,params);if(cipher==="columnar"){if(!restored.startsWith(sample))throw new Error(`self-test failed: ${cipher}`);}else if(restored!==sample)throw new Error(`self-test failed: ${cipher}`);}const unicode="déjà vu";for(const cipher of ["base64","hex"])if(decodeWithKey(encode(unicode,cipher,{}),cipher,{})!==unicode)throw new Error(`self-test failed: unicode ${cipher}`);const morse=encode("sos 123","morse",{});if(decodeWithKey(morse,"morse",{})!=="sos 123")throw new Error("self-test failed: morse");const report=analyse("Jnxr hc Arb. Gur Zngevk unf lbh. Sbyybj gur juvgr enoovg. Xabpx xabpx.",["caesar"]);if(report.candidates[0]?.params?.shift!==13||!report.candidates[0].plaintext.startsWith("Wake up Neo"))throw new Error("self-test failed: analysis");return{ok:true,tests:vectors.length+4};}
  global.DisypherEngine={version:"0.2.0-browser",analyse,encode,decodeWithKey,encodeStages,loadBank,selfTest,_internals:{plausibility,indexOfCoincidence,transformScope,crackVigenere,crackBeaufort}};
})(window);
